# ===================================
#  Import/Export Behavior Config
# ===================================

import:
    title: 'initbiz.mallimportexport::lang.import.title'
    modelClass: Initbiz\MallImportExport\Models\ProductImport
    list: $/initbiz/mallimportexport/models/product/import.yaml
    redirect: offline/mall/products

export:
    title: 'initbiz.mallimportexport::lang.export.title'
    modelClass: Initbiz\MallImportExport\Models\ProductExport
    list: $/initbiz/mallimportexport/models/product/export.yaml
    form: $/initbiz/mallimportexport/models/product/export_fields.yaml
    redirect: offline/mall/products
    fileName: 'products_export.csv'

defaultFormatOptions:
    delimiter: ';'
    enclosure: '"'
    escape: '\'
    encoding: 'utf-8'